# Exception task
Here the special class myException was created, so, I tried to throw exceptions of type myException and catch it in different functions(main(), deeper(), deeper-and-deeper()). I also used default catch(...) for all uncontrolled exceptions. See the file "report.txt", where full information about the thrown exception is situated.

